### ISSUE TITLE
Lab 2: Querying an Azure Cosmos DB Database using the SQL API :Error

### ISSUE THREAD

**Issue by sasever** [CosmosDB/labs#18]
Task 3 creates serializer errors.
PS C:\Users\sasever\Documents\cosmos\cosmoswslab3>  dotnet run

Unhandled Exception: Newtonsoft.Json.JsonSerializationException: Error converting value "["Swim Club","Culinary Club"]" to type 'System.String[]'. Path 'clubs', line 1, position 122. ---> System.ArgumentException: Could not cast or convert from System.String to System.String[].
   at Newtonsoft.Json.Utilities.ConvertUtils.EnsureTypeAssignable(Object value, Type initialType, Type targetType)
   at Newtonsoft.Json.Utilities.ConvertUtils.ConvertOrCast(Object initialValue, CultureInfo culture, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property,
JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Microsoft.Azure.Documents.QueryResult.Convert(Type type)
   at Microsoft.Azure.Documents.QueryResult.AsType[T]()
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at Microsoft.Azure.Documents.Client.FeedResponseBinder.Convert[T](FeedResponse`1 dynamicFeed)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at Microsoft.Azure.Documents.Linq.DocumentQuery`1.<GetEnumerator>d__31.MoveNext()
   at cosmoswslab3.Program.<Main>d__4.MoveNext() in C:\Users\sasever\Documents\cosmos\cosmoswslab3\Program.cs:line 38
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at cosmoswslab3.Program.<Main>(String[] args)

**Comment by sasever** [comment]
I fixed the problem by changing
task III step 19 to 

                foreach(Student student in query)
                {
                    await Console.Out.WriteLineAsync($"{student.FirstName} {student.LastName}");
                   // foreach(string club in student.Clubs)
                    foreach(string club in student.Clubs.Split(','))
                    {
                        await Console.Out.WriteLineAsync($"\t{club}");
                    }
                    await Console.Out.WriteLineAsync();
                }

and task III step 15
 public class Student
 {
     public string FirstName { get; set; }
     public string LastName { get; set; }
   //  public string[] Clubs { get; set; }
    public string Clubs { get; set; }
 }

but not sure this is the proper way since I am not much of a c# person.

**Comment by ckcampbell248** [comment]
I'm running into the same problem using the Java SDK. What it appears to be is that the columns with arrays in them such as "clubs" have quotes around the values in the source data. 

For example: "clubs":**"**[\"Photography Club\"]**"**

I don't believe that the quotes around the square brackets are valid for an array and these are being treated as strings. 

I edited the file to remove the extra quotes and also removed the backslashes used to escape the quotes embedded in the array. Then I put the data in my blob account and used it to load into my collection with ADF and now the arrays are formatted correctly in the query results and the code works as written. 

The students.json file needs to be replaced in the lab blob storage account.

**Comment by timsander1** [comment]
We have moved to new labs using our V3 .NET sdk so I am closing this issue. Let me know if you encounter anything similar with the new dataset in the new labs.
